#!/usr/bin/env bash
#this installs and vonfigures HAproxy on your server

sudo apt-get -y update
#sudo apt-get -y upgrade
sudo apt-get -y install haproxy

sudo chown -R ubuntu /etc/haproxy

configuration="\
frontend http
	bind *:80
	mode http
	default_backend web-server
backend web-server
	balance roundrobin
	server 4912-web-01 34.229.58.193:80 check
	server 4912-web-02 3.90.188.4:80 check
"

sudo echo "$configuration" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
