#!/usr/bin/env bash
#this will install the firewall ufw and setup the rules

sudo apt-get install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable